import '@radix-ui/themes/styles.css';
import './globals.css'
import './theme-config.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import NavBar from './NavBar'
import AuthProvider from './auth/Provider';
import QueryClientProvider from './QueryClientProvider';

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme accentColor="mint" radius="full" appearance="dark">
              <NavBar />
              <main className='p-5'>
                <Container>
                  {children}
                </Container>
              </main>
              <footer className="mt-10 text-center">
                Built by{' '}
                <a
                  href="https://specialcase.net/"
                  className="text-violet-500 hover:underline"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  SpecialCase
                </a>
             </footer>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
